# **SECTION 1: Brief Introduction**

## **1.1: About JC Penney**

JC Penney is a retail organisation that offers a wide range of consumer products which includes fahion, home goods, and accessories.

## **1.2: Importance/Aim of Project**

The aim of this project is to analyse JC Penney's data files and generate actionable business insights that can support product improvement, marketing strategies, and commercial decision-making.

# **SECTION 2: Loading and Understanding the Data**

## **2.1: Brief Overview**

The JC Penney Dataset consists of the following CSV and JSON files which are related to JC Penney's Online Retail Platform.

They are as follows;


*   products.csv
*   reviews.csv
*   users.csv
*   jcpenney_products.json
*   jcpenney_reviewers.json

Now, let's go ahead to load them here and understand the data set we would be working with.

## **2.2: Importing the Required Libraries**

In [ ]:
import pandas as pd               # for data manipulation and analysis
import json                       # for reading the json files
import matplotlib.pyplot as plt   # for data visualisation
import seaborn as sns             # for cleaner data visualisation

## **2.3: Loading the Data Files**

### **2.3.1:  Accessing the Data Files from my Google Drive**

In [ ]:
#This code is to enable access to the Google Drive
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

# define the path to the folder where the assignment files are stored
path = '/content/drive/MyDrive/ITNPBD2_Spring2026_Assignment/Data_Files'

# change the working directory to the specified folder
os.chdir(path)

# list all the files in the specified folder
os.listdir()

['users.csv',
 'reviews.csv',
 'jcpenney_products.json',
 'products.csv',
 'jcpenney_reviewers.json']

### **2.3.2:  Reading the CSV Data Files Using Pandas**

In [ ]:
products = pd.read_csv('products.csv')  # read the product csv files
reviews = pd.read_csv('reviews.csv')    # read the review csv files
users = pd.read_csv('users.csv')        # read the users csv files

# display the number of rows (records) and columns (attributes)
# in each data set
print("Products shape:\n", products.shape)
print("Reviews shape:\n", reviews.shape)
print("Users shape:\n", users.shape)

Products shape:
 (7982, 6)
Reviews shape:
 (39063, 4)
Users shape:
 (5000, 3)

### **2.3.3:  Reading the Products.JSON File**

In [ ]:
# create an empty list to store each JSON objects
products_json = []

# Open the JSON file in read mode ('r')
for line in open('jcpenney_products.json', 'r'):
    # convert each line (string) into a dictionary
    products_json.append(json.loads(line))

# convert the appended list of dictionaries into a pandas DataFrame
# each dictionary becomes a row in the DataFrame
products_df = pd.DataFrame(products_json)

# display the number of rows (records) and columns (attributes)
# in the Products_df
print("Products_df shape:\n", products_df.shape)

Products_df shape:
 (7982, 15)

### **2.3.4:  Reading the Reviewers.JSON File**

In [ ]:
# create an empty list to store each JSON objects
reviewers_json = []

# Open the JSON file in read mode ('r')
for line in open('jcpenney_reviewers.json', 'r'):
    # convert each line (string) into a python
    reviewers_json.append(json.loads(line))

# convert the appended list of dictionaries into a pandas DataFrame
# each dictionary becomes a row in the DataFrame
reviewers_df = pd.DataFrame(reviewers_json)

# display the number of rows (records) and columns (attributes)
# in the Reviewers_df
print("reviewers_df shape:\n", reviewers_df.shape)

reviewers_df shape:
 (5000, 4)

## **2.4:  Displaying the first 5 rows of each loaded data files**

In [ ]:
products.head()

,Uniq_id,SKU,Name,Description,Price,Av_Score
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.000
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.500
4,d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.125

In [ ]:
reviews.head()

,Uniq_id,Username,Score,Review
0,b6c0b6bea69c722939585baeac73c13d,fsdv4141,2,You never have to worry about the fit...Alfred...
1,b6c0b6bea69c722939585baeac73c13d,krpz1113,1,Good quality fabric. Perfect fit. Washed very ...
2,b6c0b6bea69c722939585baeac73c13d,mbmg3241,2,I do not normally wear pants or capris that ha...
3,b6c0b6bea69c722939585baeac73c13d,zeqg1222,0,I love these capris! They fit true to size and...
4,b6c0b6bea69c722939585baeac73c13d,nvfn3212,3,This product is very comfortable and the fabri...

In [ ]:
users.head()

   Username         DOB          State
0  bkpn1412  31.07.1983         Oregon
1  gqjs4414  27.07.1998  Massachusetts
2  eehe1434  08.08.1950          Idaho
3  hkxj1334  03.08.1969        Florida
4  jjbd1412  26.07.2001        Georgia

In [ ]:
products_df.head()

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,product_image_urls,brand,total_number_reviews,Reviews,Bought With
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'fsdv4141', 'Review': 'You never hav...","[898e42fe937a33e8ce5e900ca7a4d924, 8c02c262567..."
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,3.000,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'tpcu2211', 'Review': 'You never hav...","[bc9ab3406dcaa84a123b9da862e6367d, 18eb69e8fc2..."
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'pcfg3234', 'Review': 'You never hav...","[3ce70f519a9cfdd85cdbdecd358e5347, b0295c96d2b..."
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.500,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'ngrq4411', 'Review': 'You never hav...","[efcd811edccbeb5e67eaa8ef0d991f7c, 7b2cc00171e..."
4,d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.125,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'nbmi2334', 'Review': 'You never hav...","[0ca5ad2a218f59eb83eec1e248a0782d, 9869fc8da14..."

In [ ]:
reviewers_df.head()

,Username,DOB,State,Reviewed
0,bkpn1412,31.07.1983,Oregon,[cea76118f6a9110a893de2b7654319c0]
1,gqjs4414,27.07.1998,Massachusetts,[fa04fe6c0dd5189f54fe600838da43d3]
2,eehe1434,08.08.1950,Idaho,[]
3,hkxj1334,03.08.1969,Florida,"[f129b1803f447c2b1ce43508fb822810, 3b0c9bc0be6..."
4,jjbd1412,26.07.2001,Georgia,[]

## **2.5:  Displaying the structure and data types of each loaded data files**

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7982 entries, 0 to 7981
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Uniq_id      7982 non-null   object
 1   SKU          7915 non-null   object
 2   Name         7982 non-null   object
 3   Description  7439 non-null   object
 4   Price        5816 non-null   float64
 5   Av_Score     7982 non-null   float64
dtypes: float64(2), object(4)
memory usage: 374.3+ KB

In [ ]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39063 entries, 0 to 39062
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Uniq_id   39063 non-null  object
 1   Username  39063 non-null  object
 2   Score     39063 non-null  int64
 3   Review    39063 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.2+ MB

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  5000 non-null   object
 1   DOB       5000 non-null   object
 2   State     5000 non-null   object
dtypes: object(3)
memory usage: 117.3+ KB

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7982 entries, 0 to 7981
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uniq_id                 7982 non-null   object
 1   sku                     7982 non-null   object
 2   name_title              7982 non-null   object
 3   description             7982 non-null   object
 4   list_price              7982 non-null   object
 5   sale_price              7982 non-null   object
 6   category                7982 non-null   object
 7   category_tree           7982 non-null   object
 8   average_product_rating  7982 non-null   float64
 9   product_url             7982 non-null   object
 10  product_image_urls      7982 non-null   object
 11  brand                   7982 non-null   object
 12  total_number_reviews    7982 non-null   int64
 13  Reviews                 7982 non-null   object
 14  Bought With             7982 non-null   object
dtypes: float64(1), int64(1), object(13)
memory usage: 935.5+ KB

In [ ]:
reviewers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  5000 non-null   object
 1   DOB       5000 non-null   object
 2   State     5000 non-null   object
 3   Reviewed  5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

## **2.6:  Checking for the Unique Values in each Column of each the Data Files**

In [ ]:
for col in products.select_dtypes(include='object').columns:
    print(f"{col}: {products[col].nunique()} unique values")

Uniq_id: 7982 unique values
SKU: 6043 unique values
Name: 6001 unique values
Description: 5619 unique values

In [ ]:
for col in reviews.select_dtypes(include='object').columns:
    print(f"{col}: {reviews[col].nunique()} unique values")

Uniq_id: 7982 unique values
Username: 4993 unique values
Review: 29463 unique values

In [ ]:
for col in users.select_dtypes(include='object').columns:
    print(f"{col}: {users[col].nunique()} unique values")

Username: 4999 unique values
DOB: 52 unique values
State: 57 unique values

In [ ]:
for col in products_df.select_dtypes(include='object').columns:
    # Exclude columns that are known to contain lists,
    # or handle them separately
    if col not in ['Reviews', 'Bought With']:
        print(f"{col}: {products_df[col].nunique()} unique values")
    else:
        # For columns containing lists, you might want to count unique lists
        # or handle them differently
        # For now, we'll just print a message indicating they contain lists
        print(f"{col}: Contains lists, nunique() cannot be directly applied")

uniq_id: 7982 unique values
sku: 6044 unique values
name_title: 6002 unique values
description: 5620 unique values
list_price: 1037 unique values
sale_price: 2063 unique values
category: 1169 unique values
category_tree: 1997 unique values
product_url: 7982 unique values
product_image_urls: 6519 unique values
brand: 721 unique values
Reviews: Contains lists, nunique() cannot be directly applied
Bought With: Contains lists, nunique() cannot be directly applied

In [ ]:
for col in reviewers_df.select_dtypes(include='object').columns:
    # Exclude columns that are known to contain lists,
    # or handle them separately
    if col not in ['Reviewed']:
        print(f"{col}: {reviewers_df[col].nunique()} unique values")
    else:
        # For columns containing lists, you might want to count unique lists
        # or handle them differently
        # For now, we'll just print a message indicating they contain lists
        print(f"{col}: Contains lists, nunique() cannot be directly applied")

Username: 4999 unique values
DOB: 52 unique values
State: 57 unique values
Reviewed: Contains lists, nunique() cannot be directly applied

## **2.7:  Checking the Data Files for Missing Values**

In [ ]:
print("Missing Values in products per column:\n", products.isnull().sum())

Missing Values in products per column:
 Uniq_id           0
SKU              67
Name              0
Description     543
Price          2166
Av_Score          0
dtype: int64

In [ ]:
print("Missing Values in reviews per column:\n", reviews.isnull().sum())

Missing Values in reviews per column:
 Uniq_id     0
Username    0
Score       0
Review      0
dtype: int64

In [ ]:
print("Missing Values in users per column:\n", users.isnull().sum())

Missing Values in users per column:
 Username    0
DOB         0
State       0
dtype: int64

In [ ]:
print("Missing Values in products_df per column:\n", products_df.isnull().sum())

Missing Values in products_df per column:
 uniq_id                   0
sku                       0
name_title                0
description               0
list_price                0
sale_price                0
category                  0
category_tree             0
average_product_rating    0
product_url               0
product_image_urls        0
brand                     0
total_number_reviews      0
Reviews                   0
Bought With               0
dtype: int64

In [ ]:
print("Missing Values in reviewers_df per column:\n", reviewers_df.isnull().sum())

Missing Values in reviewers_df per column:
 Username    0
DOB         0
State       0
Reviewed    0
dtype: int64

## **2.8:  Key Observation from the Data Set Inspection**

The datasets are relationally structured, with **the reviews dataset** acting as the **central linking table** via **uniq_id** and **username**.

Missing value assessment shows complete key fields in reviews, users, and both JSON datasets. Although the products dataset has some missing values in price and description, the product IDs and rating fields are complete, which is enough for this analysis.

The JSON datasets contain extra information but also repeat details already available in the CSV files. To keep the analysis clear and within the page limit, this work will use:
*   ***reviews*** for ***central linking table*** and for ***reviews analysis***,
*   ***products*** for ***product analysis***,
*   and, ***users*** for ***demographic analysis***.

*The JSON datasets will not be used for carrying out analysis*.

# **Section 3:  Data Preparation**

## **3.1: Brief Overview of Section**

Following dataset inspection and selection, this section prepares the data for analysis by converting all the identifiers across the various data sets into lower case, creating a unified analytical dataset, and creating demographic variables (age and age groups) for segmentation.

## **3.2: Standardising the Column Names**

In [ ]:
# let's make the column names to lowercase to prevent
# an issue of case-sensitivity during merging
for df in [products, reviews, users, products_df, reviewers_df]:
    df.columns = df.columns.str.lower()
print(products.columns)

Index(['uniq_id', 'sku', 'name', 'description', 'price', 'av_score'], dtype='object')

## **3.3: Merging the Selected Data Sets**

We would now go ahead to merge the **selected data sets** mentioned in **Section 2.8**, using the **reviews data set** as the the **central linking table**.

In [ ]:
# merging reviews with products
merged_ds = pd.merge(reviews, products, on='uniq_id', how='left')

# merging merged_ds with users
merged_ds = pd.merge(merged_ds, users, on='username', how='left')

print("Merged_ds shape:\n", merged_ds.shape)

Merged_ds shape:
 (39080, 11)

In [ ]:
print(merged_ds.head())

                            uniq_id  username  score  \
0  b6c0b6bea69c722939585baeac73c13d  fsdv4141      2
1  b6c0b6bea69c722939585baeac73c13d  krpz1113      1
2  b6c0b6bea69c722939585baeac73c13d  mbmg3241      2
3  b6c0b6bea69c722939585baeac73c13d  zeqg1222      0
4  b6c0b6bea69c722939585baeac73c13d  nvfn3212      3

                                              review           sku  \
0  You never have to worry about the fit...Alfred...  pp5006380337
1  Good quality fabric. Perfect fit. Washed very ...  pp5006380337
2  I do not normally wear pants or capris that ha...  pp5006380337
3  I love these capris! They fit true to size and...  pp5006380337
4  This product is very comfortable and the fabri...  pp5006380337

                                          name  \
0  Alfred Dunner® Essential Pull On Capri Pant
1  Alfred Dunner® Essential Pull On Capri Pant
2  Alfred Dunner® Essential Pull On Capri Pant
3  Alfred Dunner® Essential Pull On Capri Pant
4  Alfred Dunner® Essential Pull On Capri Pant

                                         description  price  av_score  \
0  Youll return to our Alfred Dunner pull-on capr...  41.09     2.625
1  Youll return to our Alfred Dunner pull-on capr...  41.09     2.625
2  Youll return to our Alfred Dunner pull-on capr...  41.09     2.625
3  Youll return to our Alfred Dunner pull-on capr...  41.09     2.625
4  Youll return to our Alfred Dunner pull-on capr...  41.09     2.625

          dob                     state
0  31.07.1980            American Samoa
1  30.07.1987                  Virginia
2  08.08.1951  Northern Mariana Islands
3  28.07.1994               Connecticut
4  31.07.1980                  Oklahoma